name: myfeatness
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  introduction_screen: ^3.1.14
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.3
  build_runner: ^2.4.9
  http: ^1.2.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  cached_network_image: ^3.4.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/
    - assets/lottie/
    - assets/images/
    - assets/icon/
  # To add custom fonts to your application, add a fonts section here,
  # example:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf

flutter_native_splash:
  color: "#F3F3F3"
  image: assets/icon/splash.png
  branding: assets/icon/branding.png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/icon/splash.png
    branding: assets/icon/branding.png
    icon_background_color: "#F3F3F3"
